repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: check-yaml
-   repo: https://github.com/psf/black
    rev: 25.9.0
    hooks:
    -   id: black-jupyter
-   repo: https://github.com/kynan/nbstripout
    rev: 0.8.1
    hooks:
    -   id: nbstripout
-   repo: https://github.com/pycqa/isort
    rev: 7.0.0
    hooks:
    -   id: isort
        args: ["--profile", "black", "--filter-files"]